### ISSUE TITLE
Uso de VPN

### ISSUE THREAD

**Issue by gth1ago** [felipelobo16/bot_dizu#3]
Tava pensando em usar VPN para o caso de varias contas, tem alguma ideia para conseguir implementar? Se souber de algum rumo posso tentar atualizar pra esse uso, acho q seria uma boa, porem nunca mexi com vpn em python e se seria 'tranquilo' nas trocas de conta..

**Comment by felipelobo16** [comment]
Eu acredito que usar um proxy fique mais fácil e barato, o webdriver tem suporte pois ele simula um navegador, eu ia implementar mas não fiz por conta de estar ocupado com outras coisas mas é uma boa.

link de referencia: https://www.browserstack.com/guide/set-proxy-in-selenium
[https://3fxtqy18kygf3on3bu39kh93-wpengine.netdna-ssl.com/wp-content/uploads/2020/11/How-to-set-proxy-in-Selenium.png]<https://www.browserstack.com/guide/set-proxy-in-selenium>
How to set proxy in Selenium : Tutorial | BrowserStack<https://www.browserstack.com/guide/set-proxy-in-selenium>
What is a proxy? A proxy is an intermediary between client requests and server responses. Proxies are primarily used to ensure privacy and encapsulation between numerous interactive systems.
www.browserstack.com

________________________________
De: Gabriel Thiago ***@***.***>
Enviado: segunda-feira, 7 de junho de 2021 12:21
Para: felipelobo16/bot_dizu ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [felipelobo16/bot_dizu] Uso de VPN (#3)


Tava pensando em usar VPN para o caso de varias contas, tem alguma ideia para conseguir implementar? Se souber de algum rumo posso tentar atualizar pra esse uso, acho q seria uma boa, porem nunca mexi com vpn em python e se seria 'tranquilo' nas trocas de conta..

**Comment by gth1ago** [comment]
Show, bacana, vou dar uma lida e começar algo local nos próximos dias
